# https://docs.netlify.com/configure-builds/file-based-configuration/
# https://docs.netlify.com/configure-builds/environment-variables/

# [[headers]]
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"

# https://app.netlify.com/plugins
[[plugins]]
  package = "netlify-plugin-chromium"

[[plugins]]
  package = "netlify-plugin-image-optim"

[context.deployment]
  publish = "dist/"
  command = "yarn run build:frontend"
  environment = { NODE_VERSION = "14.17.5", NETLIFY_USE_YARN = true }
  