# https://docs.netlify.com/configure-builds/file-based-configuration/
# https://docs.netlify.com/configure-builds/environment-variables/

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[context.docs]
  base = "docs"
  publish = "build/"
  command = "yarn run build"

[context.deployment]
  publish = "dist/"
  command = "yarn run build"
  environment = { NODE_VERSION = "14.17.5", NETLIFY_USE_YARN = true }
  