# https://docs.netlify.com/configure-builds/file-based-configuration/
# https://docs.netlify.com/configure-builds/environment-variables/
# https://app.netlify.com/plugins

# [[headers]]
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "*"

[context.deployment]
  publish = "dist/"
  command = "yarn run build:frontend"
  environment = { NODE_VERSION = "14.17.5", NETLIFY_USE_YARN = true }
  